version: "3.9"

services:

  varnish:
    container_name: ${NAMESPACE}_varnish
    image: varnish:${VARNISH_VERSION}
    pull_policy: always
    env_file:
      - .env
    tmpfs:
      - /var/lib/varnish:exec
    command: "-p default_keep=300"
    depends_on:
      - webserver
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./.docker/varnish/default.vcl
        target: /etc/varnish/default.vcl
        read_only: true

  webserver:
    container_name: ${NAMESPACE}_webserver
    image: nginx:${NGINX_VERSION}
    pull_policy: always
    env_file:
      - .env
    depends_on:
      - php
    ports:
      - "8080:8080"
    command: '/usr/sbin/nginx -g "daemon off; error_log /dev/stderr info;"'
    networks:
      default:
        aliases:
          - ${SHOPURI}
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - type: bind
        source: ./.docker/nginx/config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./.docker/nginx/config/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

  php:
    container_name: ${NAMESPACE}_php
    image: osioaliu/php:${PHP_VERSION_SET}
    pull_policy: always
    sysctls:
      net.core.somaxconn: 65536
    depends_on:
      db:
        condition: service_healthy
      redis_session:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    user: ${UID_GID}
    env_file:
      - .env
    restart: on-failure
    entrypoint: [ "fixuid","docker-php-entrypoint" ]
    command: [ "php-fpm" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db_socket:/var/run/mysqld
      - app_data:${WORKDIR_SERVER}:delegated
      - composer_cache:/home/www-data/.composer:delegated
      - type: bind
        source: ./.docker/php/config/xdebug.ini
        target: /usr/local/etc/php/conf.d/xdebug.ini
        read_only: true
      - type: bind
        source: ./.docker/php/config/php-ini-overrides.ini
        target: /usr/local/etc/php/conf.d/php-ini-overrides.ini
        read_only: true
      - type: bind
        source: ./.docker/php/config/zz-docker.conf
        target: /usr/local/etc/php-fpm.d/zz-docker.conf
        read_only: true

  db:
    container_name: ${NAMESPACE}_db
    image: mariadb:${MARIADB_VERSION}
    pull_policy: always
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - .env
    healthcheck:
      test: 'mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db_socket:/var/run/mysqld
      - db_data:/var/lib/mysql/
      - type: bind
        source: ./.docker/mysql/db_dumps
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: bind
        source: ./.docker/mysql/config/my.cnf
        target: /etc/mysql/my.cnf
        read_only: true

  redis_session:
    container_name: ${NAMESPACE}_redis_session
    image: redis:${REDIS_VERSION}
    pull_policy: always
    env_file:
      - .env
    sysctls:
      net.core.somaxconn: '1024'
    entrypoint: redis-server
    command: [ "/etc/redis/redis.conf", "--appendonly", "yes" ]
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - redis_socket_session:/run/redis/
      - type: bind
        source: ./.docker/redis/redis.conf
        target: /etc/redis/redis.conf
        read_only: true

  redis_cache:
    container_name: ${NAMESPACE}_redis_cache
    image: redis:${REDIS_VERSION}
    env_file:
      - .env
    pull_policy: always
    sysctls:
      net.core.somaxconn: '1024'
    entrypoint: redis-server
    command: [ "/etc/redis/redis.conf", "--appendonly", "yes" ]
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - redis_socket_cache:/run/redis/
      - type: bind
        source: ./.docker/redis/redis.conf
        target: /etc/redis/redis.conf
        read_only: true

  opensearch:
    container_name: ${NAMESPACE}_opensearch
    image: markoshust/magento-opensearch:${OPENSEARCH_VERSION}
    env_file:
      - .env
    pull_policy: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  mailhog:
    container_name: ${NAMESPACE}_mailhog
    image: mailhog/mailhog:${MAILHOG_VERSION}
    env_file:
      - .env
    pull_policy: always
    ports:
      - ${MAILHOG_EXTERNAL_PORT}:8025
      - "1025:1025"

#  rabbitmq:
#    container_name: ${NAMESPACE}_rabbitmq
#    image: rabbitmq:${RABBITMQ_VERSION}
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin2017
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  # rabbitmq_data:
  opensearch_data:
  redis_socket_cache:
  redis_socket_session:
  db_socket:
  db_data:
  app_data:
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR}
  composer_cache:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.composer
