version: '3.8'

services:

  node:
    # build:
    #   context: ./.docker/node
    #     args:
    #       NODE_VERSION: ${NODE_VERSION}
    #       NPM_VERSION: ${NPM_VERSION}
    container_name: ${NAMESPACE}_node
    image: osioaliu/node:${NODE_VERSION}-alpine
    working_dir: /home/node/html
    tty: true
    user: node
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - app_data_node:/home/node/html:cached

volumes:
  app_data_node:
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR}